version: '3.8'

services:
  # Angular Demo
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-local
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - drugnet
    ports:
      - '80:80'

  # Spring Boot Demo API
  backend:
    volumes:
      - type: bind
        source: ./backend
        target: /app/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - drugnet
    ports:
      - '8080:8080'
networks:
  drugnet:
    driver: bridge