apiVersion: apps/v1
kind: Deployment
metadata:
  name: thedrugapi-app
  namespace: thedrugapi
  labels:
    app: thedrugapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thedrugapi-app
  template:
    metadata:
      labels:
        app: thedrugapi-app
  spec:
      containers:
        - name: thedrugapi
          image: mikelee531/thedrugapi:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: thedrugapi-service
  namespace: thedrugapi
  labels:
    app: thedrugapi-app
spec:
  type: ClusterIP
  selector:
    app: thedrugapi-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP